#!/usr/bin/env bash
#IFS
#!/usr/bin/env bash
#Read and cut
IFS=:
while read -r USERNAME PASSWORD USERID GROUP_ID USER HOME_DIRECTORY COMMAND; do
        echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USER"
done < /etc/passwd
