#!/usr/bin/env bash
#4 bad luck, 8 is your chance
x=0
while [ $x -le 10 ]; do
	if [ $x = 4 ]; then
		echo "bad luck"
	elif { $x = 8 }; then
		echo "good luch"
	else
		echo "Best School"
	fi
	((x++))
done
