#!/usr/bin/env bash
#Superstitious numbers
x=1
while [ $x -lt 21 ]; do
	case $x in
		"4")
			echo $x"bad luck from China" ;;
		"9")
			echo $x'\inbad luck from Japan' ;;
		"17")
			echo $x"\nbad luck from Italy" ;;
		*)
			echo $x ;;
	esac
	((x++))
done
