#!/usr/bin/env bash
#Superstitious numbers
x=1
while [ $x -lt 21 ]; do
	case $x in
		"4")
			echo -e $x"\nbad luck from China" ;;
		"9")
			echo -e $x"\nbad luck from Japan" ;;
		"17")
			echo -e $x"\nbad luck from Italy" ;;
		*)
			echo $x ;;
	esac
	((x++))
done
